#!/usr/bin/python

#
# Author: Branislav Blaskovic <branislav@blaskovic.sk>
# Originally made by: Lars Kellogg-Stedman
#

import sys
import optparse
import icalendar
import textwrap
import datetime
import dateutil.rrule

opts = None

def parse_args():
    p = optparse.OptionParser()
    p.add_option('-w', '--wait', action='store_true')
    p.add_option('-d', '--debug', action='store_true')
    p.add_option('-b', '--brief', action='store_true')
    p.add_option('-f', '--from', dest="from_date", default=None)

    return p.parse_args()

def from_iso(date):
    if hasattr(date, 'dt'):
        if isinstance(date.dt, datetime.date):
            return datetime.datetime.combine(date.dt, datetime.datetime.min.time())
        return date.dt
    # XXX: This is a hack to deal with ISO format dates with a terminal
    # 'Z', which aren't handled by the datetime module.
    if str(date).endswith('Z'):
        date = str(date)[:-1]
    return datetime.strptime(str(date), '%Y%m%dT%H%M%S')

def mv_attr(attr):
    if isinstance(attr, basestring):
        val = [ attr ]
    else:
        val = attr

    return val

def make_rrule(rule):
    freq = {}
    freq['DAILY'] = dateutil.rrule.DAILY
    freq['WEEKLY'] = dateutil.rrule.WEEKLY
    freq['MONTHLY'] = dateutil.rrule.MONTHLY
    freq['YEARLY'] = dateutil.rrule.YEARLY

    print rule

    #dts = list(dateutil.rrule.rrule([freq[rule.get('FREQ')[0]]], interval=10, byweekday=4, count=3))
    print dts

def get_items(event):
    items = {}
    items['summary'] = event['summary']
    items['event_start'] = from_iso(event['dtstart'])
    items['event_end'] = from_iso(event['dtend'])

    items['organizers'] = mv_attr(event.get('organizer', []))
    for i, organizer in enumerate(items['organizers']):
        if organizer.lower().startswith('mailto'):
            items['organizers'][i] = organizer[7:]

    items['attendees'] = mv_attr(event.get('attendee', []))
    for i, attendee in enumerate(items['attendees']):
        if attendee.lower().startswith('mailto'):
            items['attendees'][i] = attendee[7:]

    items['description'] = event.get('description', [])
    items['location'] = event.get('location', [])
    print event.viewvalues()
    #make_rrule(event.get('RRULE', []))
    return items

def print_vevent(event):
    global opts

    if opts.brief:
        # Print in brief layout
        print '%s = %s (%s)' % \
            (event['event_start'].strftime('%Y-%m-%d %H:%M'),
            event['summary'],
            event['location'])
    else:
        # Print full layout
        print '='*70
        print event['summary']
        print '='*70
        print

        print '       WHEN: %s - %s' % (event['event_start'].strftime('%Y-%m-%d %H:%M'), event['event_end'].strftime('%Y-%m-%d %H:%M'))
        if event['location']:
          print '      WHERE: %s' % (event['location'])
        print ' ORGANIZERS:', '\n            '.join(event['organizers'])
        print '  ATTENDING:', '\n             '.join(event['attendees'])

        if event['description']:
            print 'DESCRIPTION:', 
            initial_indent=''
            for line in event['description'].split('\n'):
                print textwrap.fill(line,
                    width=60,
                    initial_indent=initial_indent,
                    subsequent_indent='             ').encode('utf-8')
                initial_indent='             '

        print

def parse_ics(args):
    global opts

    try:
        cal = icalendar.cal.Calendar.from_ical(open(args[0]).read())
    except IndexError:
        cal = icalendar.cal.Calendar.from_ical(sys.stdin.read())

    # Fill array with events
    events = []
    for x in cal.walk():
        if x.name == 'VEVENT':
            events.append(get_items(x))
        continue
        try:
            if x.name == 'VEVENT':
                events.append(get_items(x))
        except Exception, detail:
            # Some parse error? Dont need that
            sys.stderr.write('Error: ' + str(detail) + "\n")
            continue

    # Sort by time
    events.sort(key=lambda x: x['event_start'])

    # Print these events
    for x in events:
        # Do we even want this?
        if opts.from_date and x['event_start'] < datetime.datetime.strptime(str(opts.from_date), '%Y-%m-%d'):
            continue
        print_vevent(x)

    if opts.wait:
        print 'Press RETURN to continue...'
        open('/dev/tty').readline()

def main():
    global opts
    opts, args = parse_args()
    parse_ics(args)
    return
    try:
        opts, args = parse_args()
        parse_ics(args)
    except Exception, detail:
        if opts.debug:
            raise
        else:
            print 'Failed to parse:', detail

if __name__ == '__main__':
    main()

